# Generated by Django 2.2.3 on 2019-07-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.IntegerField(choices=[(0, '领导'), (1, '实习生'), (2, '生力军')])),
                ('Power', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('education', models.IntegerField(choices=[(0, '高中'), (1, '大学'), (2, '硕士'), (3, '毕业')])),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kingadmin.Role')),
            ],
        ),
    ]
