# Generated by Django 2.2.3 on 2019-07-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingadmin', '0003_auto_20190709_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
