# Generated by Django 2.2.3 on 2019-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingadmin', '0004_auto_20190709_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sbxx',
            field=models.IntegerField(auto_created=True, blank=True, default=0),
            preserve_default=False,
        ),
    ]
