# Generated by Django 2.2.3 on 2019-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingadmin', '0005_customer_sbxx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sbxx',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
