# Generated by Django 2.2.3 on 2019-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingadmin', '0006_auto_20190709_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sbxx',
        ),
        migrations.AddField(
            model_name='customer',
            name='product_no',
            field=models.IntegerField(auto_created=True, blank=True, default=0, verbose_name='商品号'),
            preserve_default=False,
        ),
    ]
