# Generated by Django 2.2.3 on 2019-07-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingadmin', '0007_auto_20190709_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_no',
        ),
    ]
